### PR TITLE
Pin starlette to 0.10.5

### PR DESCRIPTION
**Pull request by taoufik07**
Due to some changes in starlette we need to stick with `starlette==0.10.5` for now.
ref #300

### CODE REVIEW

**Comment by tomchristie** [comment]
Pining from 0.10.x -> 0.10.5 shouldn’t be needed here. Why are folks having a Starlette 0.11 install in the first place? Is the latest PyPI release of responder not pinned to 0.10.x?

**Comment by taoufik07** [comment]
It's not released yet and starlette==0.10.6 raises "LisfespanHandler not found in routing.py "

**Comment by tomchristie** [comment]
Okay, this change isn’t needed tho. You just need a PyPI release, then.

**Comment by taoufik07** [comment]
It's needed for `pip` users

**Comment by tomchristie** [comment]
0.10.x is already correct. The problem is that there isn’t a PyPI release with it in.

**Comment by taoufik07** [comment]
Bizarre :thinking:  When using starlette 0.10.6 I got this

```python
...
  File "/home/taoufik/.../responder/responder/api.py", line 22, in <module>
    from starlette.routing import Router, LifespanHandler
ImportError: cannot import name 'LifespanHandler'
```

**Pull request merged**
