### PR TITLE
Class based websockets

### PR DESCRIPTION
**Pull request by taoufik07**
What do you guys think ?

Usage

```python
from responder.endpoints import WebSocketEndpoint

@api.route("/ws", websocket=True)
class Ws(WebSocketEndpoint):
    format = "text" # "json" by default

    async def on_connect(self, ws):
        await super().on_connect(ws) # or await ws.accept()

    async def on_receive(self, ws, data):
        await ws.send_text(data)

    async def on_disconnect(self, websocket, close_code):
        pass
```
Endpoint inspired by starlette

### CODE REVIEW

**Comment by timofurrer** [comment]
I'm not so sure - I'm in general not a big fan of dispatching via inheritance. 

However, that's definitely something @kenneth-reitz has to give his OK. 🎉

**Comment by taoufik07** [comment]
Yep I'm waiting for @kenneth-reitz, even tho I know he won't approve it xD

@timofurrer I can do the dispatching in the api and make some sort of contract (assert) to make sure the user provides the methods or at least "on_receive".

And to be honest the dispatching in responder looks messy we need to reorganize it.

**Comment by tomchristie** [comment]
This helps highlight a bigger point. What’d be ace would be if responder routed to *either* req,resp/websocket functions *or* to an ASGI application. That way responders CBV would be perfectly usable in Starlette, and Starlette’s CBVs would be perfectly usable in responder.

(So eg. you’d already have a usable websocket CBV if you wanted it, from Starlette)

I probably need to try to make some time for responder myself, to demonstrate.

**Comment by taoufik07** [comment]
@tomchristie I'm thinking of making every route a standalone app

**Pull request closed without merging**
