### PR TITLE
Endpoint request methods

### PR DESCRIPTION
**Pull request by tabotkevin**
In this update, I propose an enhancement to annotate endpoints with their accepted request types, such as "POST", "GET", "PUT", and others. The intention is to ensure appropriate handling of errors when the incoming request method does not match the expected method for an endpoint. If an endpoint lacks annotations, it defaults to accepting any request method. It's important to note that the current version of Responder only supports this functionality within class-based views.

For instance, leveraging the annotation approach:

`@api.route("/", methods=["POST"])`

This enhancement streamlines the handling of request methods, promoting more explicit endpoint definition and ensuring accurate request handling within the Responder framework.

See other examples in the `examples/enpoint_request_methods.py` file.

## Summary by CodeRabbit

- **New Features**
  - Expanded API capabilities with new route handlers for various HTTP methods.
  - Introduced asynchronous request handling for improved performance.
  - Implemented a `GreetingResource` class to manage greeting-related routes.

- **Enhancements**
  - Updated the `add_route` function to support specifying HTTP methods.

- **Tests**
  - Added tests for new endpoint request methods and route handling.

- **Documentation**
  - Adjusted documentation to reflect the new usage of HTTP methods in route declarations.

### CODE REVIEW

**Comment by kennethreitz** [comment]
I'm loving this AI haha. @tabotkevin this is looking great!

**Comment by kennethreitz** [comment]
@coderabbitai the opposite is true, the description needs to be updated, not the code.

**Comment by kennethreitz** [comment]
@coderabbitai yes, that is a correct assumption, I want the default to be ALL methods, if that makes sense.

**Comment by kennethreitz** [comment]
fine....

**Comment by tabotkevin** [comment]
The implementation here is that any HTTP method is allowed as long as none is provided. In essence, all methods are allowed when none is provided, that why the methods attribute defaults to an empty tuple.

**Pull request merged**
