### PR TITLE
Documentation: Unlock writing in Markdown, using Sphinx/MyST. Add Sphinx extensions "copybutton" and "opengraph".

### PR DESCRIPTION
**Pull request by amotl**
## About
We would like to contribute more documentation, but would like to author it in Markdown format instead of reStructuredText, thus modernizing tech writing a bit, based on excellent work of others.

## What's Inside
- [Unlock writing in Markdown, using Sphinx/MyST](https://github.com/kennethreitz/responder/pull/559/commits/eee4d5f35fc89f08b3176dd09d311a692df53294)
- [Add Sphinx extensions "copybutton" and "opengraph"](https://github.com/kennethreitz/responder/pull/559/commits/40811292a17b62d778d7a91cf93f2eaca0ea5050)

## Preview
This page is now written in Markdown, stored in markdown.md.
https://responder-testdrive.readthedocs.io/en/latest/sandbox.html
That the preview is rendering means it also works well on RTD.

## References
- [Technical advancements in Sphinx](https://community.panodata.org/t/technical-advancements-in-sphinx/278)
- [MyST - Markedly Structured Text - Parser](https://myst-parser.readthedocs.io/)
- [sphinx{design}](https://sphinx-design.readthedocs.io/)
- [sphinx-design-elements](https://sphinx-design-elements.readthedocs.io/)

### CODE REVIEW

**Comment by kennethreitz** [comment]
love this!!

**Comment by kennethreitz** [comment]
i think coderabbit is a lot better /cc @coderabbit

**Comment by amotl** [comment]
Please remove @llamareview again.

**Comment by kennethreitz** [comment]
of course, i can't figure out how to do that now lol

**Pull request merged**
