### PR TITLE
Sandbox: Add tasks configuration to pyproject.toml

### PR DESCRIPTION
**Pull request by amotl**
## About
Add best-practice configuration for sandbox tasks to `pyproject.toml`, using [poethepoet](https://pypi.org/project/poethepoet/).

## Details
The fundamental commands to use mostly, are:
- `poe format`
- `poe check`

Later, there will also be another fundamental command:
- `poe release`

Other than those, there are more supportive commands, also to build Sphinx documentation and such.

### CODE REVIEW

**Comment by kennethreitz** [comment]
can we use 'uv' for checks

**Comment by tabotkevin** [comment]
@amotl  I’m leaning towards using `uv` or `rye` for formatting, linting, and checks, with `ruff` as the underlying tool. I think the entire Python ecosystem is shifting towards `uv`. Dyne currently uses `rye`, and it’s been a breeze to work with.

**Comment by amotl** [comment]
Hi there. Thanks for your replies. If you agree in progressively modernizing the project metadata setup, and if you don't have any objections about bringing in and learning about the poethepot task runner, let's bring in this patch, and then adjust its incantation commands afterwards towards using `uv` and `rye`? I will be very happy to learn about them from your expertise, as a few friends also started using them, and I am a bit behind, just being a user of `ruff` up until now.

**Comment by amotl** [comment]
> can we use 'uv' for checks?

Because I never used `uv` before, I would need more guidance. In the current state, we apparently can't do much with `uv run`, if that is what you are referring to?

```shell
$ uv run -- echo hello
error: No `project` table found in: `/path/to/responder/pyproject.toml`
```

The same also happens with other subcommands:
```shell
$ uv tree
error: No `project` table found in: `/path/to/responder/pyproject.toml`
```

I am using:
```
$ uv version
uv 0.4.3 (Homebrew 2024-09-02)
```

**Comment by tabotkevin** [comment]
Here's a revised version:

@amotl, to provide some context: `rye` was initially intended as the main tool, planned to work with `uv` as a foundation. However, `uv` gradually started covering all of `rye`'s intended functionality, leading to the decision to prioritize `uv` over `rye`. The error you're encountering is likely because the current project wasn't created with `uv`. To fully transition the project to use `uv`, you'll need to create a new `uv` project and move all the files into the structure that `uv` sets up. This is the approach I used when I migrated Dyne to `rye`.

**Comment by kennethreitz** [comment]
Yeah, I see little reason for us to use anything but uv. I can play with it in the future, i'm glad we're in a better spot now.

**Comment by kennethreitz** [comment]
@coderabbitai can you tell us how rye shouldn't be necessary with recent uv developments?

**Comment by amotl** [comment]
> `uv` has evolved to encompass features like task management [amongst others].

I see. I am excited to see if this feature of `uv` can make `poethepoet` obsolete.

**Comment by kennethreitz** [comment]
No problem!

**Pull request merged**
